"""Trusted-default-branch workflow broker. Never executes request-supplied code."""

import hashlib
import json
import os
import random
import re
import time
from pathlib import Path
from typing import Any
from urllib.parse import quote

from .configuration import CONFIG, parse_settings
from .github import ApiError, GitHub
from .models import Envelope, Receipt, Settings, State, SubmitArgs
from .queue import Queue
from .signing import authorize, canonical
from .standard_work import StandardWork, reconcile

ISSUE_PREFIX = "[Hivemind] "


def dump(value: Any) -> str:
    return json.dumps(value, indent=2, sort_keys=True, allow_nan=False) + "\n"


class Hub:
    def __init__(self, settings: Settings, api: GitHub):
        self.settings, self.api = settings, api
        self.base = f"/repos/{settings.hub}"

    def load(self) -> tuple[str | None, State]:
        try:
            ref = self.api.get(
                f"{self.base}/git/ref/heads/{quote(self.settings.state_branch, safe='')}"
            )
        except ApiError as exc:
            if exc.status == 404:
                return None, State()
            raise
        sha = ref["object"]["sha"]
        return sha, State.model_validate(
            self.api.json_file(self.settings.hub, "state.json", sha)
        )

    def publish(self, parent: str | None, state: State, message: str) -> str:
        queue = Queue(state, self.settings)
        files = {
            "state.json": dump(state.model_dump(exclude={"receipts"})),
            "index.json": dump(queue.snapshot()),
            "queue.json": dump({p.id: [t.id for t in p.tasks] for p in state.projects}),
            "README.md": "# Hivemind state\n\nGenerated by the trusted workflow broker. Submit requests through repository Issues.\nTasks, claims, proofs, queue order, and receipts are inspectable here; history is in Git.\nOnly the protected broker App may update this state branch.\n",
        }
        for project in state.projects:
            for task in project.tasks:
                files[f"tasks/{task.id}/task.json"] = dump(
                    task.model_dump(exclude={"agent", "claim_id", "lease", "proof"})
                )
                files[f"tasks/{task.id}/claim.json"] = dump(
                    {
                        "agent": task.agent,
                        "claim_id": task.claim_id,
                        "expires_at": task.lease,
                    }
                )
                files[f"tasks/{task.id}/proof.json"] = dump(task.proof)
        for request_id, receipt in state.receipts.items():
            files[f"receipts/{request_id}.json"] = dump(receipt.model_dump())
        entries = [
            {"path": path, "mode": "100644", "type": "blob", "content": content}
            for path, content in files.items()
        ]
        tree_data: dict[str, Any] = {"tree": entries}
        if parent:
            tree_data["base_tree"] = self.api.get(f"{self.base}/git/commits/{parent}")[
                "tree"
            ]["sha"]
        tree = self.api.request(f"{self.base}/git/trees", "POST", tree_data)
        commit = self.api.request(
            f"{self.base}/git/commits",
            "POST",
            {
                "message": message,
                "tree": tree["sha"],
                "parents": [parent] if parent else [],
            },
        )
        if parent:
            self.api.request(
                f"{self.base}/git/refs/heads/{quote(self.settings.state_branch, safe='')}",
                "PATCH",
                {"sha": commit["sha"], "force": False},
            )
        else:
            self.api.request(
                f"{self.base}/git/refs",
                "POST",
                {
                    "ref": f"refs/heads/{self.settings.state_branch}",
                    "sha": commit["sha"],
                },
            )
        return commit["sha"]


def process(
    state: State,
    settings: Settings,
    issue: dict[str, Any],
    api: GitHub,
    proof_api: GitHub,
    config_sha: str,
    now: int,
) -> Receipt:
    number = issue["number"]
    body = issue.get("body") or ""
    request_id = f"invalid-issue-{number}"
    payload_hash = hashlib.sha256(body.encode()).hexdigest()
    result: dict[str, Any] = {}
    accepted = False
    envelope_record = None
    try:
        envelope = Envelope.model_validate(json.loads(body))
        envelope_record = envelope.model_dump()
        request_id = envelope.payload.request_id
        payload_hash = hashlib.sha256(
            canonical(envelope.payload.model_dump())
        ).hexdigest()
        if request_id in state.request_ids:
            raise ValueError(
                "Request ID already processed; create a fresh signed request"
            )
        actor = authorize(envelope, issue["user"]["id"], settings, now)
        if actor.startswith("github:") and not api.issue_is_unedited(
            settings.hub, number
        ):
            raise ValueError(
                "Human requests must not be edited; create a new issue instead"
            )
        working = state.model_copy(deep=True)
        queue = Queue(working, settings)
        proof = None
        if envelope.payload.action == "submit":
            args = SubmitArgs.model_validate(envelope.payload.args)
            project = queue.project(envelope.payload.project)
            task = queue.owned(project, args, actor, now)
            if queue.blockers(project, task):
                raise ValueError("Dependencies and subtasks must be complete")
            proof = proof_api.verify(
                project.repo, args.commit, args.pr, project.required_checks
            )
            if task.provenance and task.provenance.get("kind") == "standard-work":
                report_path = f".hivemind/reviews/{task.id}.md"
                try:
                    report = proof_api.text_file(project.repo, report_path, args.commit)
                except ApiError as exc:
                    if exc.status != 404:
                        raise
                    raise ValueError(
                        f"Commit the required review artifact: {report_path}"
                    ) from exc
                sections = {
                    match.lower()
                    for match in re.findall(
                        r"^#{1,6}\s+(.+?)\s*$", report, re.MULTILINE
                    )
                }
                required = {
                    "theorem references",
                    "assumptions",
                    "findings",
                    "validation",
                    "follow-ups",
                }
                if (
                    not required.issubset(sections)
                    or task.provenance["commit"] not in report
                ):
                    raise ValueError(
                        "Review must cite the source SHA and include theorem references, assumptions, findings, validation, and follow-ups headings"
                    )
                proof.update(
                    review_path=report_path,
                    review_source_sha=task.provenance["commit"],
                    review_hash=hashlib.sha256(report.encode()).hexdigest(),
                )
            proof.update(
                summary=args.summary,
                submitted_at=int(time.time()),
                config_sha=config_sha,
            )
        applied_at = max(now, int(time.time()))
        result = queue.apply(
            envelope.payload.project,
            envelope.payload.action,
            envelope.payload.args,
            actor,
            request_id,
            applied_at,
            proof,
        )
        # Commit the successful copy only. Invalid transitions cannot mutate state.
        state.projects, state.events, state.next_event_id = (
            working.projects,
            working.events,
            working.next_event_id,
        )
        accepted, message = True, "Request accepted"
    except ApiError:
        raise  # Keep requests pending after an API outage or permission failure.
    except (ValueError, KeyError, TypeError) as exc:
        message = str(exc)
    receipt_id = (
        request_id if request_id not in state.request_ids else f"replay-issue-{number}"
    )
    receipt = Receipt(
        request_id=request_id,
        issue=number,
        accepted=accepted,
        message=message,
        result=result,
        created=int(time.time()),
        payload_hash=payload_hash,
        config_sha=config_sha,
        envelope=envelope_record,
        github_id=issue.get("user", {}).get("id"),
    )
    state.receipts[receipt_id] = receipt
    state.request_ids.append(receipt_id)
    state.processed_issues[str(number)] = receipt_id
    return receipt


def notify(
    api: GitHub, settings: Settings, number: int, receipt: Receipt, sha: str
) -> None:
    status = "accepted" if receipt.accepted else "rejected"
    body = f"Hivemind request **{status}**.\n\n{receipt.message}\n\nState commit: https://github.com/{settings.hub}/commit/{sha}\n\n```json\n{dump(receipt.result)}```"
    api.request(
        f"/repos/{settings.hub}/issues/{number}/comments", "POST", {"body": body}
    )
    api.request(f"/repos/{settings.hub}/issues/{number}", "PATCH", {"state": "closed"})


def run(
    settings: Settings,
    api: GitHub,
    proof_api: GitHub,
    config_sha: str,
    standard: StandardWork | None = None,
    refresh_config: bool = False,
) -> dict[str, int]:
    hub = Hub(settings, api)
    issues = [
        i
        for i in api.pages(
            f"/repos/{settings.hub}/issues?state=open&sort=created&direction=asc"
        )
        if "pull_request" not in i and i["title"].startswith(ISSUE_PREFIX)
    ][:100]
    for attempt in range(5):
        if refresh_config:
            metadata = api.get(f"/repos/{settings.hub}")
            config_sha = api.get(
                f"/repos/{settings.hub}/commits/{metadata['default_branch']}"
            )["sha"]
            latest = parse_settings(api.text_file(settings.hub, CONFIG, config_sha))
            if latest.hub != settings.hub:
                raise ValueError(
                    "Trusted configuration changed coordinating repository"
                )
            settings = latest
            standard = settings.standard_work
            hub = Hub(settings, api)
        parent, state = hub.load()
        before = dump(state.model_dump(exclude={"receipts"}))
        queue = Queue(state, settings)
        queue.expire(int(time.time()))
        generated = (
            reconcile(state, settings, standard, api, config_sha, int(time.time()))
            if standard is not None
            else 0
        )
        notifications: list[tuple[int, Receipt]] = []
        for issue in issues:
            number = issue["number"]
            prior = state.processed_issues.get(str(number))
            if prior:
                receipt = Receipt.model_validate(
                    api.json_file(
                        settings.hub,
                        f"receipts/{prior}.json",
                        parent or settings.state_branch,
                    )
                )
            else:
                receipt = process(
                    state, settings, issue, api, proof_api, config_sha, int(time.time())
                )
            notifications.append((number, receipt))
        after = dump(state.model_dump(exclude={"receipts"}))
        if refresh_config:
            current = api.get(
                f"/repos/{settings.hub}/commits/{metadata['default_branch']}"
            )["sha"]
            if current != config_sha:
                continue  # Revalidate every operation under the latest trusted policy.
        try:
            sha = (
                hub.publish(
                    parent,
                    state,
                    f"Hivemind: reconcile {len(notifications)} requests\n\nTrusted configuration: {config_sha}",
                )
                if before != after or parent is None
                else parent
            )
        except ApiError as exc:
            if exc.status not in (409, 422) or attempt == 4:
                raise
            time.sleep(random.uniform(0.2, 0.5) * 2**attempt)
            continue
        assert sha is not None
        for number, receipt in notifications:
            try:
                notify(api, settings, number, receipt, sha)
            except ValueError:
                # State and receipt already committed; next sweep retries notification.
                print(f"Notification deferred for issue {number}")
        return {
            "processed": len(notifications),
            "accepted": sum(r.accepted for _, r in notifications),
            "generated": generated,
        }
    raise ValueError("State changed repeatedly; retry the broker")


def execute_broker(config: Path) -> dict[str, int]:
    settings = parse_settings(config.read_text())
    if os.environ.get("GITHUB_REPOSITORY", settings.hub).lower() != settings.hub:
        raise ValueError("Coordinating repository must match the workflow repository")
    if len(settings.projects) != 1 or settings.projects[0].repo.lower() != settings.hub:
        raise ValueError("Each broker must govern its own repository only")
    config_sha = os.environ.get("HIVEMIND_CONFIG_SHA", "local-development")
    api = GitHub()
    standard = settings.standard_work
    return run(settings, api, api, config_sha, standard, refresh_config=True)
